# netlify.toml

[build]
  command = "npm run build" # Komenda do uruchomienia procesu budowy
  publish = "public" # Katalog z plikami do opublikowania

[[redirects]] # Przekierowania
  from = "/*"
  to = "/index.html"
  status = 200
